"""add documents, notebooks, notebook_sources tables

Revision ID: 33fdd2d65ae2
Revises: 1215ab8a39e4
Create Date: 2026-07-24 20:43:21.572474

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "33fdd2d65ae2"
down_revision: str | None = "1215ab8a39e4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "documents",
        sa.Column("uploaded_by", sa.UUID(), nullable=False),
        sa.Column("subject_id", sa.UUID(), nullable=True),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("storage_path", sa.String(length=1024), nullable=False),
        sa.Column("mime_type", sa.String(length=127), nullable=False),
        sa.Column("file_type", sa.String(length=50), nullable=False),
        sa.Column(
            "parse_status",
            sa.Enum("pending", "processing", "done", "failed", name="document_parse_status"),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("extracted_text", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["subject_id"], ["subjects.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["uploaded_by"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_documents_subject_id"), "documents", ["subject_id"], unique=False)
    op.create_index(op.f("ix_documents_uploaded_by"), "documents", ["uploaded_by"], unique=False)
    op.create_table(
        "notebooks",
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("subject_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["subject_id"], ["subjects.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_notebooks_owner_id"), "notebooks", ["owner_id"], unique=False)
    op.create_index(op.f("ix_notebooks_subject_id"), "notebooks", ["subject_id"], unique=False)
    op.create_table(
        "notebook_sources",
        sa.Column("notebook_id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column(
            "indexing_status",
            sa.Enum("pending", "indexed", "failed", name="notebook_source_index_status"),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["notebook_id"], ["notebooks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "notebook_id", "document_id", name="uq_notebook_sources_notebook_document"
        ),
    )
    op.create_index(
        op.f("ix_notebook_sources_document_id"), "notebook_sources", ["document_id"], unique=False
    )
    op.create_index(
        op.f("ix_notebook_sources_notebook_id"), "notebook_sources", ["notebook_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_notebook_sources_notebook_id"), table_name="notebook_sources")
    op.drop_index(op.f("ix_notebook_sources_document_id"), table_name="notebook_sources")
    op.drop_table("notebook_sources")
    op.drop_index(op.f("ix_notebooks_subject_id"), table_name="notebooks")
    op.drop_index(op.f("ix_notebooks_owner_id"), table_name="notebooks")
    op.drop_table("notebooks")
    op.drop_index(op.f("ix_documents_uploaded_by"), table_name="documents")
    op.drop_index(op.f("ix_documents_subject_id"), table_name="documents")
    op.drop_table("documents")
    # ### end Alembic commands ###
    # Autogenerate doesn't drop native Postgres enum types on downgrade; without this,
    # a downgrade-then-upgrade cycle fails with "type already exists".
    sa.Enum(name="notebook_source_index_status").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="document_parse_status").drop(op.get_bind(), checkfirst=True)
