"""add quiz attempt and weak topic tables

Revision ID: 5dd50c43344f
Revises: 8ed81029dcc4
Create Date: 2026-08-11 17:03:09.510200

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5dd50c43344f"
down_revision: str | None = "8ed81029dcc4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# create_type=False: op.create_table's inline sa.Enum(...) creates the Postgres type
# implicitly on CREATE TABLE but op.drop_table does not emit a matching DROP TYPE, so a
# downgrade leaves the type orphaned and a subsequent upgrade fails with
# "type already exists". Explicit create()/drop() below avoids that, same pattern as
# migration 8ed81029dcc4 (there needed because the enum was shared across two tables;
# here needed because op.create_table/op.drop_table just don't manage type lifecycle).
quiz_attempt_status = postgresql.ENUM(
    "in_progress",
    "submitted",
    "grading",
    "graded",
    "abandoned",
    name="quiz_attempt_status",
    create_type=False,
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    quiz_attempt_status.create(op.get_bind(), checkfirst=True)
    op.create_table(
        "weak_topics",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("notebook_id", sa.UUID(), nullable=False),
        sa.Column("topic", sa.Text(), nullable=False),
        sa.Column("missed_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("last_detected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["notebook_id"], ["notebooks.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_weak_topics_notebook_id"), "weak_topics", ["notebook_id"], unique=False
    )
    op.create_index(op.f("ix_weak_topics_user_id"), "weak_topics", ["user_id"], unique=False)
    op.create_index(
        "ix_weak_topics_user_id_notebook_id",
        "weak_topics",
        ["user_id", "notebook_id"],
        unique=False,
    )
    op.create_table(
        "quiz_attempts",
        sa.Column("quiz_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            quiz_attempt_status,
            server_default="in_progress",
            nullable=False,
        ),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("time_limit_seconds", sa.Integer(), nullable=True),
        sa.Column(
            "question_order",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column(
            "answers", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("score", sa.Numeric(), nullable=True),
        sa.Column("max_score", sa.Numeric(), nullable=True),
        sa.Column("graded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["quiz_id"], ["quizzes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_quiz_attempts_quiz_id"), "quiz_attempts", ["quiz_id"], unique=False)
    op.create_index(op.f("ix_quiz_attempts_user_id"), "quiz_attempts", ["user_id"], unique=False)
    op.create_table(
        "quiz_attempt_answers",
        sa.Column("attempt_id", sa.UUID(), nullable=False),
        sa.Column("question_id", sa.UUID(), nullable=False),
        sa.Column("student_answer", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_correct", sa.Boolean(), nullable=True),
        sa.Column("score", sa.Numeric(), server_default="0", nullable=False),
        sa.Column("ai_feedback", sa.Text(), nullable=True),
        sa.Column("topic_tag", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["attempt_id"], ["quiz_attempts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["question_id"], ["questions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_quiz_attempt_answers_attempt_id"),
        "quiz_attempt_answers",
        ["attempt_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_quiz_attempt_answers_question_id"),
        "quiz_attempt_answers",
        ["question_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_quiz_attempt_answers_question_id"), table_name="quiz_attempt_answers")
    op.drop_index(op.f("ix_quiz_attempt_answers_attempt_id"), table_name="quiz_attempt_answers")
    op.drop_table("quiz_attempt_answers")
    op.drop_index(op.f("ix_quiz_attempts_user_id"), table_name="quiz_attempts")
    op.drop_index(op.f("ix_quiz_attempts_quiz_id"), table_name="quiz_attempts")
    op.drop_table("quiz_attempts")
    quiz_attempt_status.drop(op.get_bind(), checkfirst=True)
    op.drop_index("ix_weak_topics_user_id_notebook_id", table_name="weak_topics")
    op.drop_index(op.f("ix_weak_topics_user_id"), table_name="weak_topics")
    op.drop_index(op.f("ix_weak_topics_notebook_id"), table_name="weak_topics")
    op.drop_table("weak_topics")
    # ### end Alembic commands ###
