"""add notebooklm_notebook_id to notebooks

Revision ID: 8e7b2b0b803f
Revises: 33fdd2d65ae2
Create Date: 2026-07-24 21:24:20.732247

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8e7b2b0b803f"
down_revision: str | None = "33fdd2d65ae2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "notebooks", sa.Column("notebooklm_notebook_id", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("notebooks", "notebooklm_notebook_id")
    # ### end Alembic commands ###
