"""add quizzes and questions tables

Revision ID: 8ed81029dcc4
Revises: 5d81c8fe607b
Create Date: 2026-08-11 16:50:29.387293

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8ed81029dcc4"
down_revision: str | None = "5d81c8fe607b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


quiz_status = postgresql.ENUM(
    "pending", "generating", "done", "failed", name="quiz_status", create_type=False
)
# Shared by quizzes.difficulty and questions.difficulty -- created/dropped once here,
# not per-column, since native_enum columns on two tables would otherwise each try to
# CREATE/DROP the same Postgres type.
quiz_difficulty = postgresql.ENUM(
    "easy", "medium", "hard", "mixed", name="quiz_difficulty", create_type=False
)
question_type = postgresql.ENUM(
    "mcq",
    "true_false",
    "fill_blank",
    "matching",
    "assertion_reason",
    "short_answer",
    "long_answer",
    "case_study",
    name="question_type",
    create_type=False,
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    quiz_status.create(op.get_bind(), checkfirst=True)
    quiz_difficulty.create(op.get_bind(), checkfirst=True)
    question_type.create(op.get_bind(), checkfirst=True)
    op.create_table(
        "quizzes",
        sa.Column("notebook_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("topic", sa.String(length=255), nullable=True),
        sa.Column("status", quiz_status, server_default="pending", nullable=False),
        sa.Column(
            "question_types",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("question_count", sa.Integer(), nullable=False),
        sa.Column("difficulty", quiz_difficulty, nullable=False),
        sa.Column("time_limit_seconds", sa.Integer(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["notebook_id"], ["notebooks.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_quizzes_notebook_id"), "quizzes", ["notebook_id"], unique=False)
    op.create_index(op.f("ix_quizzes_user_id"), "quizzes", ["user_id"], unique=False)
    op.create_table(
        "questions",
        sa.Column("quiz_id", sa.UUID(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("question_type", question_type, nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column(
            "type_data",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("correct_answer", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("reference_answer", sa.Text(), nullable=True),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column("difficulty", quiz_difficulty, nullable=False),
        sa.Column("citation", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["quiz_id"], ["quizzes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_questions_quiz_id"), "questions", ["quiz_id"], unique=False)
    op.create_index(
        "ix_questions_quiz_id_position", "questions", ["quiz_id", "position"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_questions_quiz_id_position", table_name="questions")
    op.drop_index(op.f("ix_questions_quiz_id"), table_name="questions")
    op.drop_table("questions")
    op.drop_index(op.f("ix_quizzes_user_id"), table_name="quizzes")
    op.drop_index(op.f("ix_quizzes_notebook_id"), table_name="quizzes")
    op.drop_table("quizzes")
    question_type.drop(op.get_bind(), checkfirst=True)
    quiz_difficulty.drop(op.get_bind(), checkfirst=True)
    quiz_status.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
