"""add include_web_search to quizzes

Revision ID: a7146e33121d
Revises: a67d2f4c91be
Create Date: 2026-08-13 10:37:43.124656

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a7146e33121d"
down_revision: str | None = "a67d2f4c91be"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "quizzes",
        sa.Column("include_web_search", sa.Boolean(), server_default="false", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # Rollback note: drops the column outright (no backfill/data-loss concern -- the
    # column carries no data other than a per-quiz opt-in flag, so downgrading loses
    # only the recorded opt-in choice, not source content).
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("quizzes", "include_web_search")
    # ### end Alembic commands ###
