"""add notes flashcard_sets and flashcards tables

Revision ID: ccb307816929
Revises: 4c92ea8ada77
Create Date: 2026-08-10 17:26:10.150717

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ccb307816929"
down_revision: str | None = "4c92ea8ada77"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


flashcard_set_status = postgresql.ENUM(
    "pending", "generating", "done", "failed", name="flashcard_set_status", create_type=False
)
note_material_type = postgresql.ENUM(
    "note", "study_guide", name="note_material_type", create_type=False
)
note_status = postgresql.ENUM(
    "pending", "generating", "done", "failed", name="note_status", create_type=False
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    flashcard_set_status.create(op.get_bind(), checkfirst=True)
    note_material_type.create(op.get_bind(), checkfirst=True)
    note_status.create(op.get_bind(), checkfirst=True)
    op.create_table(
        "flashcard_sets",
        sa.Column("notebook_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("status", flashcard_set_status, server_default="pending", nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["notebook_id"], ["notebooks.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_flashcard_sets_notebook_id"), "flashcard_sets", ["notebook_id"], unique=False
    )
    op.create_index(op.f("ix_flashcard_sets_user_id"), "flashcard_sets", ["user_id"], unique=False)
    op.create_table(
        "notes",
        sa.Column("notebook_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("material_type", note_material_type, nullable=False),
        sa.Column("status", note_status, server_default="pending", nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column(
            "citations",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["notebook_id"], ["notebooks.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_notes_notebook_id"), "notes", ["notebook_id"], unique=False)
    op.create_index(op.f("ix_notes_user_id"), "notes", ["user_id"], unique=False)
    op.create_table(
        "flashcards",
        sa.Column("flashcard_set_id", sa.UUID(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("front", sa.Text(), nullable=False),
        sa.Column("back", sa.Text(), nullable=False),
        sa.Column("citation", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["flashcard_set_id"], ["flashcard_sets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_flashcards_flashcard_set_id"), "flashcards", ["flashcard_set_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_flashcards_flashcard_set_id"), table_name="flashcards")
    op.drop_table("flashcards")
    op.drop_index(op.f("ix_notes_user_id"), table_name="notes")
    op.drop_index(op.f("ix_notes_notebook_id"), table_name="notes")
    op.drop_table("notes")
    op.drop_index(op.f("ix_flashcard_sets_user_id"), table_name="flashcard_sets")
    op.drop_index(op.f("ix_flashcard_sets_notebook_id"), table_name="flashcard_sets")
    op.drop_table("flashcard_sets")
    note_status.drop(op.get_bind(), checkfirst=True)
    note_material_type.drop(op.get_bind(), checkfirst=True)
    flashcard_set_status.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
