"""add title description source_url to documents

Adds optional resource metadata (title, description) and link-resource
support (source_url) to `documents`. `storage_path` becomes nullable since
a link-backed document has no uploaded bytes; a CHECK constraint enforces
exactly one of `storage_path`/`source_url` is set.

Rollback note: downgrade drops the new columns and constraint and restores
`storage_path NOT NULL` — safe only if no link-backed documents (source_url
IS NOT NULL) exist, since those rows have no storage_path to satisfy the
restored constraint.

Revision ID: d0205eedee3a
Revises: 8e7b2b0b803f
Create Date: 2026-08-10 13:23:41.179801

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d0205eedee3a"
down_revision: str | None = "8e7b2b0b803f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("documents", sa.Column("source_url", sa.String(length=2048), nullable=True))
    op.add_column("documents", sa.Column("title", sa.String(length=255), nullable=True))
    op.add_column("documents", sa.Column("description", sa.Text(), nullable=True))
    op.alter_column(
        "documents", "storage_path", existing_type=sa.VARCHAR(length=1024), nullable=True
    )
    op.create_check_constraint(
        "ck_documents_exactly_one_of_storage_path_source_url",
        "documents",
        "(storage_path IS NOT NULL) != (source_url IS NOT NULL)",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "ck_documents_exactly_one_of_storage_path_source_url", "documents", type_="check"
    )
    op.alter_column(
        "documents", "storage_path", existing_type=sa.VARCHAR(length=1024), nullable=False
    )
    op.drop_column("documents", "description")
    op.drop_column("documents", "title")
    op.drop_column("documents", "source_url")
    # ### end Alembic commands ###
