"""add generated_materials table

Revision ID: ec638c027c98
Revises: ccb307816929
Create Date: 2026-08-10 19:07:43.155728

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ec638c027c98"
down_revision: str | None = "ccb307816929"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


material_artifact_type = postgresql.ENUM(
    "audio",
    "report",
    "slides",
    "infographic",
    "mindmap",
    "data_table",
    name="material_artifact_type",
    create_type=False,
)
material_status = postgresql.ENUM(
    "pending", "generating", "done", "failed", name="material_status", create_type=False
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    material_artifact_type.create(op.get_bind(), checkfirst=True)
    material_status.create(op.get_bind(), checkfirst=True)
    op.create_table(
        "generated_materials",
        sa.Column("notebook_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("artifact_type", material_artifact_type, nullable=False),
        sa.Column("status", material_status, server_default="pending", nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column(
            "options", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("notebooklm_artifact_id", sa.String(length=255), nullable=True),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("storage_path", sa.String(length=500), nullable=True),
        sa.Column("mime_type", sa.String(length=100), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["notebook_id"], ["notebooks.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_generated_materials_notebook_id"),
        "generated_materials",
        ["notebook_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_generated_materials_user_id"), "generated_materials", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_generated_materials_user_id"), table_name="generated_materials")
    op.drop_index(op.f("ix_generated_materials_notebook_id"), table_name="generated_materials")
    op.drop_table("generated_materials")
    material_status.drop(op.get_bind(), checkfirst=True)
    material_artifact_type.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
