"""add topic column to questions

Revision ID: efa782cf4ee7
Revises: 5dd50c43344f
Create Date: 2026-08-11 18:35:59.649858

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "efa782cf4ee7"
down_revision: str | None = "5dd50c43344f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("questions", sa.Column("topic", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("questions", "topic")
    # ### end Alembic commands ###
